name       : python-nbclassic
version    : 0.4.8
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/n/nbclassic/nbclassic-0.4.8.tar.gz : c74d8a500f8e058d46b576a41e5bc640711e1032cf7541dde5f73ea49497e283
homepage   : https://jupyter.org/
license    : BSD-3-Clause
component  : programming.python
summary    : A web-based notebook environment for interactive computing
description: |
    The Jupyter NbClassic is a web application that allows you to create and share documents that contain live code, equations, visualizations, and explanatory text. The NbClassic has support for multiple programming languages, sharing, and interactive widgets.
rundeps    :
    - python-ipython_genutils
    - python-jupyter-server
    - python-notebook-shim
build      : |
    %python3_setup
install    : |
    %python3_install
